from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('', views.home),
    path('articles', views.ArticlesList.as_view(), name='articles_list'),
    path('articles/create', views.ArticleCreateView.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', views.ArticleUpdate.as_view(), name='articles_edit'),
    path("article/delete", views.del_article, name='del_article'),
    path('langs', views.LangsList.as_view(), name='langs_list'),
    path('langs/create', views.LngCreateView.as_view(), name='create_lang'),
    path('langs/<int:pk>/edit', views.LangsUpdate.as_view(), name='lang_update'),
    path('langs/delete', views.delete_langs, name='lang_del'),
    path("site_infos", views.StaticUpdate.as_view(), name='static_info'),
    path('images/save', views.save_images, name='images_save'),
    path("images/delete", views.delete_image, name='del-img'),
    path("settings", views.FormSettings.as_view()),
    path('translations', views.TranslationList.as_view(), name='translation_list'),
    path("translations/<int:pk>", views.TranslationGroupDetail.as_view(), name='transl_group_detail'),
    path('translation/edit', views.translation_update, name='translation_edit'),
    path("translations/<int:pk>/edit", views.TranslationGroupUdpate.as_view(), name='transl_group_edit'),
    path("translation/delete", views.delete_translation, name='del_transl'),
    path("translation_group/create", views.add_trans_group, name='transl_group_create'),
    path('article_categories', views.ArticleCtgList.as_view(), name='article_ctg_list'),
    path('article_categories/create', views.AddArticleCtg.as_view(), name='add_acticle_ctg'),
    path("article_categories/<int:pk>/edit", views.ArticleCtgEdit.as_view(), name='article_ctg_update'),
    path('article_categories/delete', views.article_ctg_del, name='del_art_ctg'),
    path("faq", views.FAQlist.as_view(), name='faq_list'),
    path("faq/create", views.FAQcreate.as_view(), name='faq_create'),
    path('faq/<int:pk>/edit', views.FAQupdate.as_view(), name='faq_edit'),
    path("events", views.EventsList.as_view(), name='events_list'),
    path('events/create', views.EventsCreate.as_view(), name="events_create"),
    path("events/<int:pk>/edit", views.EventsUpdate.as_view(), name='events_update'),
    path("delete", views.delete_item, name='delete'),
    path('delete_alot', views.delete_alot, name='del_alot'),
    path("lang_icon_delete", views.del_lang_icon, name='lang_icon_del'),
    path("add_static_image", views.add_static_image, name='add_static_logos'),
    path("delete_static_image", views.del_statics_image, name='del_static_image'),
    path('delete_article_ctg_images', views.delete_article_group_img, name='art_ctg_image_del'),
    path("about_us", views.AboutUsView.as_view(), name='about_us'),
    path("about_us/video/delete", views.delete_about_video, name='del_about_video'),
    path('about_us/video/set', views.set_about_video, name='set_about_video'),
    path('services', views.ServicesList.as_view(), name='services'),
    path("services/create", views.ServiceCreate.as_view(), name='services_create'),
    path("services/<int:pk>/edit", views.ServicesUpdate.as_view(), name='services_update'),
    path("delete_service_image", views.del_sev_image, name='del_serv_image'),
    path('login', LoginView.as_view(
        template_name='admin/sing-in.html',
        success_url='/admin/',
    ), name = 'login_admin'),
    path('admins', views.AdminsList.as_view(), name='admin_list'),
    path("admins/create", views.AdminCreate.as_view(), name='admins_create'),
    path("admins/<int:pk>/edit", views.AdminUpdate.as_view(), name='admins_edit'),
    path("delete_article_image", views.delete_article_image, name='del_article_img')
]
