# Generated by Django 4.1 on 2023-01-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimages',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.RemoveField(
            model_name='services',
            name='meta_field',
        ),
        migrations.RemoveField(
            model_name='services',
            name='parent',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsImages',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
