# Generated by Django 4.1 on 2023-01-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_aboutusimages_parent_delete_partners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.JSONField(blank=True, null=True, verbose_name='Title')),
                ('title_second', models.JSONField(blank=True, null=True, verbose_name='Title')),
                ('text_first', models.JSONField(blank=True, null=True, verbose_name='Text')),
                ('text_second', models.JSONField(blank=True, null=True, verbose_name='Text')),
                ('video', models.FileField(blank=True, null=True, upload_to='about_us', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, null=True, verbose_name='Title')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='partner_images')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, null=True, verbose_name='Title')),
                ('sub_title', models.JSONField(blank=True, null=True, verbose_name='Sub title')),
                ('deckription', models.JSONField(blank=True, null=True, verbose_name='Deckription')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='service_images')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('meta_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.metatags')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.services')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='about_us_images')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admins.aboutus')),
            ],
        ),
    ]
