# Generated by Django 4.1 on 2023-01-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_aboutus_partners_services_aboutusimages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translations',
            unique_together={('key', 'group')},
        ),
    ]
