# Generated by Django 4.1 on 2023-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_translations_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranlsationgroups',
            name='sub_text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
