# Generated by Django 4.1 on 2023-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_tranlsationgroups_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranlsationgroups',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
