# Generated by Django 4.1 on 2023-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_tranlsationgroups_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranlsationgroups',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
