# Generated by Django 4.1 on 2023-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_tranlsationgroups_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinformation',
            name='subtitle',
            field=models.JSONField(blank=True, null=True, verbose_name='Подзаголовок сайта'),
        ),
    ]
