# Generated by Django 4.1 on 2023-02-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_staticinformation_nbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admins.articlecategories'),
        ),
    ]
