# Generated by Django 4.1 on 2023-02-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_services_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='admins.metatags'),
            preserve_default=False,
        ),
    ]
