# Generated by Django 4.1 on 2023-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_articles_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatags',
            name='meta_tags',
        ),
        migrations.AddField(
            model_name='metatags',
            name='meta_deck',
            field=models.JSONField(blank=True, null=True, verbose_name='Meta desk'),
        ),
    ]
