# Generated by Django 4.1 on 2023-02-09 09:25

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_alter_articles_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='rev_image')),
                ('title', models.JSONField(blank=True, null=True, verbose_name='Title')),
                ('text', models.JSONField(blank=True, null=True, verbose_name='Text')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
