# Generated by Django 4.1 on 2023-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinformation',
            name='nbm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
